// This file was automatically generated by JAFF.
// This file could be overwritten.

// ABOUTME: Header file for chemistry ODE system using header-only integrators (VODE)
// ABOUTME: Auto-generated by JAFF for solving chemical reaction networks

#ifndef CHEMISTRY_ODE_HPP
#define CHEMISTRY_ODE_HPP

#include <array>
#include <cmath>
#include <integrators/integrators.hpp>

struct ChemistryODE {
    // Number of species in the chemical network
    // PREPROCESS_NUM_SPECIES

    static constexpr int neqs = 14;

    // PREPROCESS_END

    using state_type = std::array<integrators::Real, neqs>;
    using rhs_type = std::array<integrators::Real, neqs>;
    using jacobian_type = std::array<std::array<integrators::Real, neqs>, neqs>;

    // Species indices and common constants
    // PREPROCESS_COMMONS

    static constexpr int idx_hj = 0;
    static constexpr int idx_e = 1;
    static constexpr int idx_h = 2;
    static constexpr int idx_c = 3;
    static constexpr int idx_cj = 4;
    static constexpr int idx_coj = 5;
    static constexpr int idx_co = 6;
    static constexpr int idx_o = 7;
    static constexpr int idx_ch2 = 8;
    static constexpr int idx_ch = 9;
    static constexpr int idx_n2 = 10;
    static constexpr int idx_n = 11;
    static constexpr int idx_n2j = 12;
    static constexpr int idx_h2 = 13;
    static constexpr int nspecs = 14;
    static constexpr int nreactions = 15;
    
    // Common chemistry variables used in rate expressions
    // These should typically be passed as parameters or computed from the state
    static constexpr double DEFAULT_TEMPERATURE = 300.0;  // Default gas temperature in K
    static constexpr double DEFAULT_AV = 1.0;             // Default visual extinction
    static constexpr double DEFAULT_CRATE = 1.3e-17;      // Default cosmic ray ionization rate

    // PREPROCESS_END

    // Evaluate the ODE right-hand side: dy/dt = f(t, y)
    static void rhs(const integrators::Real /*t*/, const state_type& y, rhs_type& f) {
        // PREPROCESS_TEMP_VARS

        // Temperature and environment variables used in chemical reactions
        // T is expected to be passed as a parameter or computed from the state
        const double tgas = DEFAULT_TEMPERATURE;
        const double tdust = DEFAULT_TEMPERATURE;
        const double av = DEFAULT_AV;  // Visual extinction
        const double crate = DEFAULT_CRATE;  // Cosmic ray ionization rate

        // PREPROCESS_END

        // Alias species concentrations to `nden` to match generated code
        const auto& nden = y;

        // Compute reaction rates
        // PREPROCESS_NUM_REACTIONS

        double k[15];

        // PREPROCESS_END

        // PREPROCESS_RATES

        k[0] = 2.6022447615079392e-10*std::pow(std::min(300.0, tgas), -0.75);
        k[1] = 0.46000000000000002*crate;
        k[2] = 3.3900000000000002e-10*std::exp(-3.7610000000000001*av);
        k[3] = 1.4272387941535721e-10*std::pow(tgas, -0.60999999999999999);
        k[4] = 2.0e-14;
        k[5] = 9.9999999999999995e-21;
        k[6] = 1.0000000000000001e-33;
        k[7] = 1.2999999999999999e-12;
        k[8] = photorates(8, 13.6000000000000, 1.00000000000000e+99);
        k[9] = photorates(9, 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000., 1.00000000000000e+99);
        k[10] = 5.0*crate;
        k[11] = 1.2200000000000001e-12;
        k[12] = 7.4000000000000003e-11;
        k[13] = 5.6e-11*std::sqrt(tgas)*std::exp(-102124.0/tgas);
        k[14] = 4.2999999999999999e-13;

        // PREPROCESS_END

        // Compute derivatives for each species
        // PREPROCESS_ODE

        const double cse0 = 0.46000000000000002*crate*nden[2];
        const double cse1 = photorates(0, 13.6, 9.9999999999999997e+98)*nden[2];
        const double cse2 = 2.6022447615079392e-10*nden[0]*nden[1]*std::pow(std::min(300.0, tgas), -0.75);
        const double cse3 = cse0 + cse1 - cse2;
        const double cse4 = 3.3900000000000002e-10*std::exp(-3.7610000000000001*av)*nden[3];
        const double cse5 = 1.4272387941535721e-10*std::pow(tgas, -0.60999999999999999)*nden[1]*nden[4];
        const double cse6 = 1.2999999999999999e-12*nden[6];
        const double cse7 = 2.0e-14*nden[1]*nden[5];
        const double cse8 = cse6 - cse7;
        const double cse9 = photorates(1, 1.0e+99, 9.9999999999999997e+98)*nden[8];
        const double cse10 = std::sqrt(tgas)*std::exp(-102124.0/tgas)*nden[1]*nden[13];
        const double cse11 = 9.9999999999999995e-21*nden[3]*nden[7];
        const double cse12 = -cse4 + cse5;
        const double cse13 = 7.4430000000000008e-11*nden[6]*nden[12];
        const double cse14 = -cse13;
        const double cse15 = crate*nden[10];
        const double cse16 = std::pow(nden[11], 2);
        f[0] = cse3;
        f[1] = cse3 + cse4 - cse5 + cse8;
        f[2] = -cse0 - cse1 + 1.12e-10*cse10 + cse2 + cse9;
        f[3] = -cse11 + cse12 + 1.0000000000000001e-33*nden[6];
        f[4] = -cse12;
        f[5] = cse13 + cse8;
        f[6] = cse11 + cse14 - cse6 + cse7;
        f[7] = -cse11 + 1.0000000000000001e-33*nden[6];
        f[8] = -cse9;
        f[9] = cse9;
        f[10] = cse13 - 5.0*cse15 + 1.2200000000000001e-12*cse16;
        f[11] = 10.0*cse15 - 2.4400000000000001e-12*cse16;
        f[12] = cse14;
        f[13] = -5.6e-11*cse10;

        // PREPROCESS_END
    }

    // Evaluate the Jacobian matrix: J_ij = df_i/dy_j
    static void jacobian(const integrators::Real /*t*/, const state_type& y, jacobian_type& J) {
        // PREPROCESS_TEMP_VARS

        // Temperature and environment variables used in chemical reactions
        // T is expected to be passed as a parameter or computed from the state
        const double tgas = DEFAULT_TEMPERATURE;
        const double tdust = DEFAULT_TEMPERATURE;
        const double av = DEFAULT_AV;  // Visual extinction
        const double crate = DEFAULT_CRATE;  // Cosmic ray ionization rate

        // PREPROCESS_END

        // Alias species concentrations to `nden` to match generated code
        const auto& nden = y;

        // Zero the Jacobian matrix before filling non-zero entries
        for (int ii = 0; ii < neqs; ++ii) {
            for (int jj = 0; jj < neqs; ++jj) {
                J[static_cast<size_t>(ii)][static_cast<size_t>(jj)] = 0.0;
            }
        }

        // Compute reaction rates (needed for Jacobian evaluation)
        // PREPROCESS_NUM_REACTIONS

        double k[15];

        // PREPROCESS_END

        // PREPROCESS_RATES

        k[0] = 2.6022447615079392e-10*std::pow(std::min(300.0, tgas), -0.75);
        k[1] = 0.46000000000000002*crate;
        k[2] = 3.3900000000000002e-10*std::exp(-3.7610000000000001*av);
        k[3] = 1.4272387941535721e-10*std::pow(tgas, -0.60999999999999999);
        k[4] = 2.0e-14;
        k[5] = 9.9999999999999995e-21;
        k[6] = 1.0000000000000001e-33;
        k[7] = 1.2999999999999999e-12;
        k[8] = photorates(8, 13.6000000000000, 1.00000000000000e+99);
        k[9] = photorates(9, 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000., 1.00000000000000e+99);
        k[10] = 5.0*crate;
        k[11] = 1.2200000000000001e-12;
        k[12] = 7.4000000000000003e-11;
        k[13] = 5.6e-11*std::sqrt(tgas)*std::exp(-102124.0/tgas);
        k[14] = 4.2999999999999999e-13;

        // PREPROCESS_END

        // Compute analytical Jacobian
        // PREPROCESS_JACOBIAN

        const double cse0 = 2.6022447615079392e-10*std::pow(std::min(300.0, tgas), -0.75);
        const double cse1 = cse0*nden[1];
        const double cse2 = -cse1;
        const double cse3 = cse0*nden[0];
        const double cse4 = 0.46000000000000002*crate + photorates(0, 13.6, 9.9999999999999997e+98);
        const double cse5 = 2.0e-14*nden[5];
        const double cse6 = 1.4272387941535721e-10*std::pow(tgas, -0.60999999999999999);
        const double cse7 = cse6*nden[4];
        const double cse8 = 3.3900000000000002e-10*std::exp(-3.7610000000000001*av);
        const double cse9 = cse6*nden[1];
        const double cse10 = -cse9;
        const double cse11 = 2.0e-14*nden[1];
        const double cse12 = -cse11;
        const double cse13 = std::sqrt(tgas)*std::exp(-102124.0/tgas);
        const double cse14 = 1.12e-10*cse13;
        const double cse15 = photorates(1, 1.0e+99, 9.9999999999999997e+98);
        const double cse16 = 9.9999999999999995e-21*nden[7];
        const double cse17 = 9.9999999999999995e-21*nden[3];
        const double cse18 = -cse17;
        const double cse19 = 7.4430000000000008e-11*nden[12];
        const double cse20 = cse19 + 1.2999999999999999e-12;
        const double cse21 = 7.4430000000000008e-11*nden[6];
        const double cse22 = -cse21;
        const double cse23 = 5.6e-11*cse13;
        J[0][0] = cse2;
        J[0][1] = -cse3;
        J[0][2] = cse4;
        J[1][0] = cse2;
        J[1][1] = -cse3 - cse5 - cse7;
        J[1][2] = cse4;
        J[1][3] = cse8;
        J[1][4] = cse10;
        J[1][5] = cse12;
        J[1][6] = 1.2999999999999999e-12;
        J[2][0] = cse1;
        J[2][1] = cse14*nden[13] + cse3;
        J[2][2] = -cse4;
        J[2][8] = cse15;
        J[2][13] = cse14*nden[1];
        J[3][1] = cse7;
        J[3][3] = -cse16 - cse8;
        J[3][4] = cse9;
        J[3][6] = 1.0000000000000001e-33;
        J[3][7] = cse18;
        J[4][1] = -cse7;
        J[4][3] = cse8;
        J[4][4] = cse10;
        J[5][1] = -cse5;
        J[5][5] = cse12;
        J[5][6] = cse20;
        J[5][12] = cse21;
        J[6][1] = cse5;
        J[6][3] = cse16;
        J[6][5] = cse11;
        J[6][6] = -cse20;
        J[6][7] = cse17;
        J[6][12] = cse22;
        J[7][3] = -cse16;
        J[7][6] = 1.0000000000000001e-33;
        J[7][7] = cse18;
        J[8][8] = -cse15;
        J[9][8] = cse15;
        J[10][6] = cse19;
        J[10][10] = -5.0*crate;
        J[10][11] = 2.4400000000000001e-12*nden[11];
        J[10][12] = cse21;
        J[11][10] = 10.0*crate;
        J[11][11] = -4.8800000000000002e-12*nden[11];
        J[12][6] = -cse19;
        J[12][12] = cse22;
        J[13][1] = -cse23*nden[13];
        J[13][13] = -cse23*nden[1];

        // PREPROCESS_END
    }
};

#endif // CHEMISTRY_ODE_HPP
