from __future__ import annotations

import shutil
from pathlib import Path
from typing import TYPE_CHECKING

from ..io._logger import JaffLogger

if TYPE_CHECKING:
    import logging


class Preprocessor:
    def __init__(self):
        self.logger: logging.Logger = JaffLogger().get_logger()

    # loop on the files in the fnames list and replace the pragmas from the dictionaries
    # this also copies all the files that are not in the fnames list but are in the path
    def preprocess(
        self,
        path: str | Path,
        fnames: list[str] | str,
        dictionaries: list[dict[str, str]] | dict[str, str],
        comment: str = "!!",
        add_header: bool = True,
        path_build: str | Path | None = None,
    ) -> None:
        if isinstance(fnames, str):
            fnames = [fnames]

        if not isinstance(dictionaries, list):
            dictionaries = [dictionaries]

        path_obj = Path(path)
        build_dir = Path(path_build) if path_build is not None else Path.cwd()

        # create the build path if it does not exist
        build_dir.mkdir(parents=True, exist_ok=True)

        # preprocess the files in the fnames list first
        for fname, dictionary in zip(fnames, dictionaries):
            self.preprocess_file(
                path_obj / fname,
                dictionary,
                comment=comment,
                add_header=add_header,
                path_build=build_dir,
            )

        # copy files that are not in the fnames list
        for file in path_obj.iterdir():
            if file.name in fnames or not file.is_file():
                continue

            self.logger.info(f"Copying {file} to {build_dir}")
            shutil.copyfile(file, build_dir / file.name)

    # preprocess a single file replacing the pragmas with the values from the dictionary
    # this also adds a header to the file
    # comment is the string that starts the pragma
    def preprocess_file(
        self,
        fname: str | Path,
        dictionary: dict[str, str],
        comment: str = "!!",
        add_header: bool = True,
        path_build: str | Path | None = None,
    ) -> None:
        file_path = Path(fname)

        # Auto-detect comment style based on file extension if not explicitly set
        if comment == "auto":
            ext = file_path.suffix.lower()
            if ext == ".cmake" or file_path.name.lower() == "cmakelists.txt":
                comment = "#"
            elif ext in [".cpp", ".hpp", ".h", ".cc"]:
                comment = "//"
            elif ext in [".f90", ".f"]:
                comment = "!!"
            elif ext == ".py":
                comment = "#"
            # else keep the default

        full_pragma = f"{comment} PREPROCESS_"
        in_pragma = False

        with open(file_path) as fh:
            out = ""

            if add_header:
                out += f"{comment} This file was automatically generated by JAFF.\n"
                out += f"{comment} This file could be overwritten.\n\n"

            for row in fh:
                srow = row.strip()
                if srow.startswith(full_pragma) and srow != f"{full_pragma}END":
                    nspace = row.split(comment)[0].count(" ")
                    pragma_key = srow.replace(full_pragma, "")
                    if pragma_key not in dictionary:
                        out += row
                        continue
                    in_pragma = True
                    pragma = dictionary[pragma_key]
                    indent = " " * nspace
                    this_pragma = (
                        row
                        + "\n"
                        + indent
                        + pragma.replace("\n", "\n" + indent).rstrip()
                        + "\n\n"
                    )
                    # this removes the indent in the fortran pragmas (fpp)
                    out += this_pragma  # "\n".join([x.lstrip() if is_fpp(x) else x for x in this_pragma.split("\n")])
                    continue

                if srow == f"{full_pragma}END":
                    in_pragma = False

                if in_pragma:
                    continue

                out += row

            build_dir = Path(path_build) if path_build is not None else Path.cwd()
            fname_build = build_dir / file_path.name

            self.logger.info(f"Preprocessing {file_path} -> {fname_build}")
            with open(fname_build, "w") as fout:
                fout.write(out)
