// ABOUTME: Header file for chemistry ODE system using header-only integrators
// (VODE) ABOUTME: Auto-generated by JAFF for solving chemical reaction networks

#ifndef CHEMISTRY_ODE_HPP
#define CHEMISTRY_ODE_HPP

#include <array>
#include <cmath>
#include <integrators/integrators.hpp>

struct ChemistryODE {
  // Number of species in the chemical network
  // $JAFF SUB nspec
  static constexpr int neqs = $nspec$;
  // $JAFF END

  using state_type = std::array<integrators::Real, neqs>;
  using rhs_type = std::array<integrators::Real, neqs>;
  using jacobian_type = std::array<std::array<integrators::Real, neqs>, neqs>;

  // Species indices and common constants
  // $JAFF REPEAT idx, specie_with_normalized_sign IN species_with_normalized_sign
  static constexpr int idx_$specie_with_normalized_sign$ = $idx$;
  // $JAFF END
  // $JAFF SUB nspec,nreact
  static constexpr int nspecs = $nspec$;
  static constexpr int nreactions = $nreact$;
  // $JAFF END

  // Common chemistry variables used in rate expressions
  // These should typically be passed as parameters or computed from the state
  static constexpr double DEFAULT_TEMPERATURE =
      300.0;                                // Default gas temperature in K
  static constexpr double DEFAULT_AV = 1.0; // Default visual extinction
  static constexpr double DEFAULT_CRATE =
      1.3e-17; // Default cosmic ray ionization rate
  // Evaluate the ODE right-hand side: dy/dt = f(t, y)
  static void rhs(const integrators::Real /*t*/, const state_type &y,
                  rhs_type &f) {
    // Temperature and environment variables used in chemical reactions
    // T is expected to be passed as a parameter or computed from the state
    const double tgas = DEFAULT_TEMPERATURE;
    const double tdust = DEFAULT_TEMPERATURE;
    const double av = DEFAULT_AV;       // Visual extinction
    const double crate = DEFAULT_CRATE; // Cosmic ray ionization rate

    // Alias species concentrations to `nden` to match generated code
    const auto &nden = y;

    // Compute reaction rates
    // $JAFF SUB nreact
    double k[$nreact$];
    // $JAFF END

    // $JAFF REPEAT idx, rate IN rates
    k[$idx$] = $rate$;
    // $JAFF END

    // Compute derivatives for each species
    // $JAFF REPEAT idx, ode, cse IN odes
    const double cse$idx$ = $cse$;
    f[$idx$] = $ode$;
    // $JAFF END
  }

  // Evaluate the Jacobian matrix: J_ij = df_i/dy_j
  static void jacobian(const integrators::Real /*t*/, const state_type &y,
                       jacobian_type &J) {
    // Temperature and environment variables used in chemical reactions
    // T is expected to be passed as a parameter or computed from the state
    const double tgas = DEFAULT_TEMPERATURE;
    const double tdust = DEFAULT_TEMPERATURE;
    const double av = DEFAULT_AV;       // Visual extinction
    const double crate = DEFAULT_CRATE; // Cosmic ray ionization rate

    // Alias species concentrations to `nden` to match generated code
    const auto &nden = y;

    // Zero the Jacobian matrix before filling non-zero entries
    for (int ii = 0; ii < neqs; ++ii) {
      for (int jj = 0; jj < neqs; ++jj) {
        J[static_cast<size_t>(ii)][static_cast<size_t>(jj)] = 0.0;
      }
    }

    // Compute reaction rates (needed for Jacobian evaluation)
    // $JAFF SUB nreact
    double k[$nreact$];
    // $JAFF END

    // $JAFF REPEAT idx, rate IN rates
    k[$idx$] = $rate$;
    // $JAFF END

    // Compute analytical Jacobian
    // $JAFF REPEAT idx, expr, cse IN jacobian
    const double cse$idx$ = $cse$;
    J[$idx$][$idx$] = $expr$;
    // $JAFF END
  }
};

#endif // CHEMISTRY_ODE_HPP
